### ISSUE TITLE
Do status labels show task status or item status?

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#39]
<img width="292" alt="screen shot 2015-09-25 at 09 54 58" src="https://cloud.githubusercontent.com/assets/13318121/10102361/feb75afc-636b-11e5-9317-f575c120e074.png">

**Comment by TristanWright** [comment]
Perhaps have a "Rerun" button for items in this state?

**Comment by cjh1** [comment]
Good question @jourdain Do you have a view on this?

**Comment by jourdain** [comment]
I don't think you can re-run a task/simulation. Otherwise all your previously generated data will be lost.
For that you should clone your ran simulation and run the new one that should have kept all the config and input information.

And if I'm off,  that's probably because I didn't properly understood the question. ;-)
